spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8070   #控制台地址
  application:
    name: springboot-init
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    # session 配置
    session:
       cookie:
         max-age: 2592000
#         domain: linhaijian.top
#         domain: 111.230.23.40,localhost
       store-type: redis
      # 30 天过期
       timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.122.29:3306/jackdaw-api?useUnicode=true&characterEncoding=utf8
    username: root
    password: SBnightwatch777_
  # Redis 配置
  redis:
    database: 0
    host: 120.25.122.29
    port: 6379
    timeout: 5000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
#        domain: linhaijian.top
      store-type: redis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
#    address: nacos://111.230.23.40:8848
jackdaw:
  openai:
    api-key: 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
    api-host: https://api.openai.com/
    proxy-host-name: 127.0.0.1
    proxy-port: 7890
  api:
    access-key: jyaucpk629371039cjdkttest
    secret-key: yospousjh182hbssasasd