spring:
  application:
    name: jackdawAPI-inerface
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8070   #控制台地址
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    #    host: 120.25.122.29
    host: localhost
    port: 6379
    timeout: 5000
server:
  port: 8123
  servlet:
    context-path: /
yuapi:
  client:
    access-key: yupi
    secret-key: abcdefgh
